services:
  mysql:
    image: mysql:8.4
    container_name: bradar-cinema-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bradar_cinema
      MYSQL_USER: bradar
      MYSQL_PASSWORD: bradar
    ports:
      - "13306:3306"
    volumes:
      - bradar_cinema_mysql_data:/var/lib/mysql

volumes:
  bradar_cinema_mysql_data:
